name: x_responsive
description: Utils for creating responsive widgets.
version: 0.2.0
homepage: https://github.com/TaipaXu/x_responsive
repository: https://github.com/TaipaXu/x_responsive
issue_tracker: https://github.com/TaipaXu/x_responsive/issues

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
